export const DATABASE_DISPLAY_REQUEST = "DATABASE_DISPLAY_REQUEST";
export const DATABASE_DISPLAY_SUCCESS = "DATABASE_DISPLAY_SUCCESS";
export const DATABASE_DISPLAY_FAIL = "DATABASE_DISPLAY_FAIL";

export const BESTACCURACY_DISPLAY_REQUEST = "BESTACCURACY_DISPLAY_REQUEST";
export const BESTACCURACY_DISPLAY_SUCCESS = "BESTACCURACY_DISPLAY_SUCCESS";
export const BESTACCURACY_DISPLAY_FAIL = "BESTACCURACY_DISPLAY_FAIL";