const synonyms = {
    "paham": ["tahu", "mengerti"],
    "periksa": ["cek", "lihat", "cocok"],
    "beda": ["lain"],
    "ganggu": ["masalah", "kelainan", "persoalan", "keluh"],
    "cerita": ["kabar"],
    "komunikasi": ["hubungan", "interaksi"],
    "amati": ["pantau", "awasi", "monitor", "observasi"],
    "aktivitas": ["kegiatan", "pekerjaan", "laku", "tindak"],
    "manfaat": ["keuntungan", "kegunaan", "fungsi", "guna", "khasiat", "faedah", "untung"],
    "BAB": ["pup", "berak", "buang air besar"],
    "BAK": ["kencing", "buang air kecil", "pipis", "air seni"],
    "partisipasi": ["ikut", "kontribusi", "gabung"],
    "terlaksana": ["terjadi"],
    "peran": ["tugas", "fungsi"],
    "rutin": ["konsisten", "kontinu", "berulang", "berkelanjutan"],
    "keluarga": ["kerabat", "anak", "suami", "pengasuh", "keturunan"],
    "saran": ["masukan", "anjukan", "usul", "rekomendasi", "arah", "panduan"],
    "hamil": ["kandungan", "mengandung", "bunting"],
    "sesak": ["sumpek", "pengap", "senat", "sendak", "asak", "sendat"],
    "hambatan": ["gangguan", "persoalan", "hambat", "rintangan"],
    "ubah": ["tukar", "pindai", "pindah", "alih", "silih"],
    "tensi": ["tekanan darah"],
    "nyeri": ["perih", "sakit", "ngilu", "linu", "lara", "perih"],
    "kondisi": ["keadaan", "situasi"],
    "aset": ["barang", "harta", "uang", "kekayaan", "finansial"],
    "tinggal": ["huni", "menetap"],
    "dampak": ["akibat", "efek", "imbas", "konsekuensi", "impak"],
    "konsentasi": ["fokus"],
    "kolaborasi": ["kerjasama"],
    "istirahat": ["tidur", "bobok", "rebah", "baring", "molor"],
    "identitas": ["gelang"],
    "struktur": ["pola", "motif", "model", "desain", "corak", "bentuk"],
    "konsumsi": ["makan", "minum"],
    "obat": ["medikasi", "penawar", "remedi"],
    "variasi": ["jenis", "macam"],
    "kualitas": ["taraf"],
    "emosi": ["marah", "galak"],
    "lemah": ["letih", "lunglai", "lelah", "lesu"],
    "dekat": ["lekat"],
    "harapan": ["cita", "impian"],
    "sejak": ["semenjak"],
    "sikap": ["perilaku"],
    "rumah": ["hunian"],
    "rawat": ["jaga"],
    "memandang": ["melihat", "memaknai"],
    "budaya": ["adat", "tradisi", "kebiasaan", "nilai"],
    "bertentangan": ["bentrok", "berbenturan", "bertubrukan"],
    "ibadah": ["ibadat", "sembahyang", "salat", "doa"],
    "sering": ["kerap", "rajin", "selalu", "frekuensi"],
    "komunitas": ["kelompok", "paguyuban", "populasi", "perkumpulan", "golongan"],
    "respon": ["tanggapan", "perlakuan"]
}

const toUse = {

}

module.exports = {synonyms}