name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    if: github.ref == 'refs/heads/master'

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    
    - run: npm install
    - run: npm run build --if-present
    
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: ./*
        remote_path: "${{ secrets.VIRTUAL_DEPLOY_PATH }}"
        remote_host: "${{ secrets.VIRTUAL_DEPLOY_HOST }}"
        remote_user: "${{ secrets.VIRTUAL_DEPLOY_USER }}"
        remote_key: "${{ secrets.VIRTUAL_DEPLOY_SECRET }}"
        
    - name: Create env file
      run: |
        touch .env
        echo MONGO_URI =${POSTGRES_USER} > .env
        cat .env
      env: 
        MONGO_URI: ${{ secrets.MONGO_URI }} 
