name: Staging Pasien Virtual

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    if: github.ref == 'refs/heads/master'

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    
    - run: npm install
    - run: npm run build --if-present
    
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: ./*
        remote_path: "${{ secrets.VIRTUAL_DEPLOY_PATH }}"
        remote_host: "${{ secrets.VIRTUAL_STAGING_DEPLOY_HOST }}"
        remote_user: "${{ secrets.VIRTUAL_DEPLOY_USER }}"
        remote_key: "${{ secrets.VIRTUAL_DEPLOY_SECRET }}"
