name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    if: github.ref == 'refs/heads/master'

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    
    - run: npm install
    - run: npm run build --if-present
    
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: ./*
        remote_path: "${{ secrets.VIRTUAL_DEPLOY_PATH }}"
        remote_host: "${{ secrets.VIRTUAL_DEPLOY_HOST }}"
        remote_user: "${{ secrets.VIRTUAL_DEPLOY_USER }}"
        remote_key: "${{ secrets.VIRTUAL_DEPLOY_SECRET }}"

  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DEBUG: false
        envkey_SOME_API_KEY: "MONGO_URI"
        envkey_SECRET_KEY: ${{ secrets.MONGO_URI }}
        some_other_variable: foobar
        directory: ${{ secrets.VIRTUAL_DEPLOY_PATH }}
        file_name: .env
        fail_on_empty: false
